### ISSUE TITLE
npm install fails on Node.js v12

### ISSUE THREAD

**Issue by ruixingw** [Aveek-Saha/MusicPlayer#12]
I just started to learn javascript/Nodejs and this project seems a very good example to start with. However, I got the following error during "npm install". My nodejs version is 12.8.1 and npm version is 6.10.2. 

Searching, it seems due to a removed API since Node 10. 
Switching to Node 8.9.4 solved the problem, but I was wondering if you have a plan to update the code to be compatible with newer versions of Node?

Thank you.

```
..
..
../src/rabin_wrap.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE RabinWrap::Configure(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/rabin_wrap.cc:52:47: error: no matching function for call to ‘v8::Value::Uint32Value()’
   handle->average_bits = info[0]->Uint32Value();
..
..
..
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-55-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ruixingw/MusicPlayer/node_modules/rabin-bindings
gyp ERR! node -v v12.8.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm WARN DuskPlayer@3.0.0 No repository field.
..
..
..
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rabin-bindings@1.7.4 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rabin-bindings@1.7.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ruixingw/.npm/_logs/2019-08-17T00_00_34_219Z-debug.log
```

**Comment by Aveek-Saha** [comment]
This application has been built on node v10.15.2 and npm v6.10.2. 
As of now the latest LTS version of node is v10, when new LTS versions are released I'll check for breaking changes and update the application if needed, but I don't plan to update the code for the latest node versions.

**Comment by ruixingw** [comment]
Thanks.
