### ISSUE TITLE
"run dist" does not exist and "run build" errors

### ISSUE THREAD

**Issue by thoni56** [Aveek-Saha/MusicPlayer#28]
How do I build a distribution of this? When I do

    npm run dist

as the README.md says that does not exist. And

    npm run build

crashes with

 ```
MusicPlayer/node_modules/electron-builder/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/thoni56/Utveckling/MusicPlayer/node_modules/electron-builder/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
```

**Comment by Aveek-Saha** [comment]
The command on the readme should be updated to `npm run build`. However on running `npm run build` I was unable to recreate the issue. 

Are you trying to build from an external drive? If so that might be the issue as indicated here: https://github.com/electron-userland/electron-builder/issues/4045#issuecomment-656293236

**Comment by thoni56** [comment]
I removed everything and re-cloned and now it worked so there was probably something wrong with my copy, or something I did when trying variations on "npm run..." until I got the bright idea to look in `package.json` ;-)

So all is well. After that minor update in the README, of course.

Thanks.

**Comment by Aveek-Saha** [comment]
The README has been updated
